_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNNLogisticGMM"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "../../../data/VOC-Detection/faster-rcnn/IOU_FFN/model_final.pth"

#  PROPOSAL_GENERATOR:
#    NAME: "RPNLogistic"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "ROIHeadsLogisticGMMNewLimitFPEnergy_IouLoss_FFN"
    NUM_CLASSES: 20
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_custom_train',)
  TEST: ('voc_custom_val',)
SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.02
  STEPS: (12000, 25000)
  MAX_ITER: 36000 # 17.4 epochs
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 2000
VOS:
  STARTING_ITER: 12000
  SAMPLE_NUMBER: 1000
DATALOADER:
    NUM_WORKERS: 8  # Depends on the available memory